#!/bin/bash
# Script to fetch submodules for CAM
# if argument -internal-only is supplied then only checkout CAM internal submodules, otherwise checkout everything needed for
# cam as a top level repository
#
git clone -n https://github.com/frgomes/bash-scripts --depth 1
pushd bash-scripts
git checkout HEAD -- bin/git_sparse_checkout
popd
# Start with sparse checkouts

./bash-scripts/bin/git_sparse_checkout  https://github.com/larson-group/clubb_release clubb_4ncar_20221129_59cb19f_branch src/physics/clubb -- src/CLUBB_core/ src/SILHS/
git restore src/physics/clubb

./bash-scripts/bin/git_sparse_checkout https://github.com/CFMIP/COSPv2.0 master src/physics/cosp2/src -- src/
git restore src/physics/cosp2/src

./bash-scripts/bin/git_sparse_checkout https://github.com/MPAS-Dev/MPAS-Model.git develop src/dynamics/mpas/dycore -- src/external/ src/operators/ src/tools/ \
                      src/core_atmosphere/ src/framework/
git restore src/dynamics/mpas/dycore

submodules=('chem_proc' 'src/physics/carma/base' 'src/physics/pumas' 'src/physics/pumas-frozen' 'src/physics/ali_arms' 'src/atmos_phys' 'src/dynamics/fv3/atmos_cubed_sphere' 'src/hemco')
for mod in "${submodules[@]}"
do
   echo "Initializing $mod"
   git submodule update --init $mod
done

if [ $# -gt 0 ]
  then
    exit 0
fi


submodules=('ccs_config' 'components/cice5' 'components/cice' 'components/cmeps' \
           'components/cdeps' 'components/cpl7' 'share' 'libraries/mct' \
           'libraries/parallelio' 'cime' 'libraries/FMS' 'components/mosart' \
           'components/rtm')

for mod in "${submodules[@]}"
do
   echo "Initializing $mod"
   git submodule update --init --recursive $mod
done

sparse_submodules=('components/clm' 'components/cism')
for mod in "${sparse_submodules[@]}"
do
   echo "Initializing $mod"
   git submodule update --init $mod
   pushd $mod
   bash ./install -internal-only
   popd
done
