! Beljaars Sub-Grid Orographic (SGO) Form Drag Parameterization
! Returns drag profile and integrated stress associated with subgrid mountains
! with horizontal length scales nominally below 3 km.
! Based on Beljaars et al. (2004, QJRMS) https://doi.org/10.1256/qj.03.73.
!
! Original author: J. Bacmeister, March 2016, based on TMS
module beljaars_drag
  implicit none
  private

  public :: beljaars_drag_run

contains
!> \section arg_table_beljaars_drag_run Argument Table
!! \htmlinclude beljaars_drag_run.html
  ! Compute Beljaars SGO form drag profile and surface stresses
  subroutine beljaars_drag_run( &
    do_beljaars, &
    ncol, pver, &
    u, v, t, pmid, delp, zm, sgh30, &
    gravit, &
    ! below output:
    drag, taux, tauy, &
    errmsg, errflg)
    use ccpp_kinds, only: kind_phys

    logical,            intent(in)  :: do_beljaars  ! is Beljaars active?
    integer,            intent(in)  :: ncol
    integer,            intent(in)  :: pver
    real(kind_phys),    intent(in)  :: u(:, :)      ! zonal wind [m s-1]
    real(kind_phys),    intent(in)  :: v(:, :)      ! meridional wind [m s-1]
    real(kind_phys),    intent(in)  :: t(:, :)      ! air temperature [K]
    real(kind_phys),    intent(in)  :: pmid(:, :)   ! air pressure [Pa]
    real(kind_phys),    intent(in)  :: delp(:, :)   ! air pressure thickness [Pa]
    real(kind_phys),    intent(in)  :: zm(:, :)     ! geopotential height wrt surface [m]
    real(kind_phys),    intent(in)  :: sgh30(:)     ! standard deviation of subgrid orography [m]
    real(kind_phys),    intent(in)  :: gravit       ! gravitational acceleration [m s-2]

    real(kind_phys),    intent(out) :: drag(:, :)   ! SGO drag profile [s-1]
    real(kind_phys),    intent(out) :: taux(:)      ! surface zonal wind stress [N m-2]
    real(kind_phys),    intent(out) :: tauy(:)      ! surface meridional wind stress [N m-2]
    character(len=*),   intent(out) :: errmsg
    integer,            intent(out) :: errflg

    ! Local variables
    integer  :: i, k

    real(kind_phys) :: vmag                         ! velocity magnitude [m s-1]

    real(kind_phys) :: alpha, beta, Cmd, Ccorr, n1, n2, k1, kflt, k2, IH
    real(kind_phys) :: a1(ncol), a2(ncol)

    errmsg = ''
    errflg = 0

    if(.not. do_beljaars) then
      ! if not doing Beljaars, return zero drag and stresses from routine.
      drag(:,:) = 0._kind_phys
      taux(:,:) = 0._kind_phys
      tauy(:,:) = 0._kind_phys
      return
    end if

    alpha =  12.0_kind_phys
    beta  =  1.0_kind_phys
    n1    = -1.9_kind_phys
    n2    = -2.8_kind_phys

    Cmd   = 0.005_kind_phys
    Ccorr = 0.6_kind_phys * 5.0_kind_phys

    kflt  = 0.00035_kind_phys   ! m-1
    k1    = 0.003_kind_phys     ! m-1
    IH    = 0.00102_kind_phys   ! m-1

    a1(1:ncol) = (sgh30(1:ncol) * sgh30(1:ncol)) / (IH * (kflt**n1))
    a2(1:ncol) = a1(1:ncol) * k1**(n1 - n2)

    do k = 1, pver
      do i = 1, ncol
        vmag      = sqrt(u(i, k)**2 + v(i, k)**2)
        drag(i, k) = -alpha * beta * Cmd * Ccorr * vmag * 2.109_kind_phys * &
                     exp(-(zm(i, k) / 1500.0_kind_phys) * sqrt(zm(i, k) / 1500.0_kind_phys)) * &
                     (zm(i, k)**(-1.2_kind_phys)) * a2(i)
      end do
    end do

    ! Diagnose effective surface drag in X and Y by integrating in the vertical
    !
    ! taux, tauy stresses generated by Beljaars drag here
    ! uses the pre-vertical diffusion winds (and not the updated winds)
    ! however, at this point only these winds are available because the diffusion
    ! solver runs after the orographic drag.
    ! the actual provisionally updated winds are actually used to recompute taubljx/y
    ! which are added to the updated residual stress. see the physics scheme
    ! beljaars_add_updated_residual_stress. (hplin, 5/13/26)
    taux(:) = 0.0_kind_phys
    tauy(:) = 0.0_kind_phys
    do k = 1, pver
      do i = 1, ncol
        taux(i) = taux(i) + drag(i, k) * u(i, k) * delp(i, k) / gravit
        tauy(i) = tauy(i) + drag(i, k) * v(i, k) * delp(i, k) / gravit
      end do
    end do

  end subroutine beljaars_drag_run
end module beljaars_drag
