vi cam4_port/shell_commands       
vi dae/shell_commands            
vi outfrq1d/shell_commands                  
vi outfrq3d/shell_commands          
vi outfrq9s_amie/shell_commands   
vi           reduced_hist1d/shell_commands 
vi       waccmx_weimer/shell_commands
vi cam5_port_f45/shell_commands  
vi  dartcambigens/shell_commands  
vi outfrq1d_amie/shell_commands             
vi outfrq3h/shell_commands          
vi outfrq9s_mg3/shell_commands  
vi             reduced_hist3s/shell_commands
vi cam5_port_ne30/shell_commands 
vi  fire_emis/shell_commands      
vi outfrq1d_newyear/shell_commands          
vi outfrq3s_refined/shell_commands  
vi outfrq9s_refined_camchem/shell_commands
vi   reduced_hist5d/shell_commands
vi cam6_port_f09/shell_commands  
vi nudging/shell_commands        
vi outfrq1d_refined_camchem/shell_commands  
vi outfrq9s/shell_commands          
vi outfrq9s_sd/shell_commands 
vi               scam_mpace_outfrq9s/shell_commands
vi cosp/shell_commands  
vi           nuopc_cap/shell_commands      
vi outfrq1m/shell_commands                  
vi outfrq9s_576tsks/shell_commands  
vi outfrq9s_wcm_ne30/shell_commands       
vi   silhs/shell_commands

